name: Additional

on: [push, pull_request]

# Required shell entrypoint to have properly activated conda environments
defaults:
  run:
    shell: bash -l {0}

jobs:
  doctest:
    runs-on: "ubuntu-latest"
    timeout-minutes: 90
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3.0.1
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          channel-priority: strict
          python-version: "3.11"
          environment-file: continuous_integration/environment-3.11.yaml
          activate-environment: test-environment
          auto-activate-base: false

      - name: Install
        run: source continuous_integration/scripts/install.sh

      - name: Run tests
        run: pytest -v --doctest-modules --ignore-glob='*/test_*.py' dask

  imports:
    runs-on: "ubuntu-latest"
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3.0.1
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          channel-priority: strict
          python-version: "3.9"
          activate-environment: test-environment
          auto-activate-base: false

      - name: Run import tests
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: source continuous_integration/scripts/test_imports.sh
